# Basic https://www.jekyll.com.cn/docs/configuration/
title: iOS/Mac Development Engineering
user: dgynfi
subtitle: Personal Website
description: dgynfi's blog
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: dgynfi
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: iOSre / Anti
url: "https://dgynfi.github.io"
mainEntityOfPage: "https://dgynfi.github.io/archive/"

# Comment
comment:
    disqus: iOS/Mac/Flutter/...
    # uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·
    gitment: yes

gitcomments:
    repo: githubpages-comments
    client_id: eb8baa6afd018fb78abf
    client_secret: c7b3a1a69585b929f76b9b849a5266c6198d8498


# Social
social:
    github: dgynfi
    mail: vinphy.teng@foxmail.com
    technical_exchange_group: 155353383.

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: e7f6d46714fcd28fb24be011203bee5f  

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
    id: UA-111030597-1
    host: auto  

Params: 
    Search: ç«™å†…æœç´¢

# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://dgynfi.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}   
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}      
    - {title: å…³äºæˆ‘, description: about, url: '/about'}      
    

# Pagination åˆ†é¡µåŠŸèƒ½
plugins: [jekyll-paginate,jekyll-sitemap,jekyll-feed]
paginate: 20
paginate_path: "page/:num/"

